In [75]:
import numpy as np

print(np.__version__)

1.23.3

In [76]:
import pandas as pd

df = pd.read_csv('data.csv')
df

,Make,Model,Year,Engine Fuel Type,Engine HP,Engine Cylinders,Transmission Type,Driven_Wheels,Number of Doors,Market Category,Vehicle Size,Vehicle Style,highway MPG,city mpg,Popularity,MSRP
0,BMW,1 Series M,2011,premium unleaded (required),335.0,6.0,MANUAL,rear wheel drive,2.0,"Factory Tuner,Luxury,High-Performance",Compact,Coupe,26,19,3916,46135
1,BMW,1 Series,2011,premium unleaded (required),300.0,6.0,MANUAL,rear wheel drive,2.0,"Luxury,Performance",Compact,Convertible,28,19,3916,40650
2,BMW,1 Series,2011,premium unleaded (required),300.0,6.0,MANUAL,rear wheel drive,2.0,"Luxury,High-Performance",Compact,Coupe,28,20,3916,36350
3,BMW,1 Series,2011,premium unleaded (required),230.0,6.0,MANUAL,rear wheel drive,2.0,"Luxury,Performance",Compact,Coupe,28,18,3916,29450
4,BMW,1 Series,2011,premium unleaded (required),230.0,6.0,MANUAL,rear wheel drive,2.0,Luxury,Compact,Convertible,28,18,3916,34500
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11909,Acura,ZDX,2012,premium unleaded (required),300.0,6.0,AUTOMATIC,all wheel drive,4.0,"Crossover,Hatchback,Luxury",Midsize,4dr Hatchback,23,16,204,46120
11910,Acura,ZDX,2012,premium unleaded (required),300.0,6.0,AUTOMATIC,all wheel drive,4.0,"Crossover,Hatchback,Luxury",Midsize,4dr Hatchback,23,16,204,56670
11911,Acura,ZDX,2012,premium unleaded (required),300.0,6.0,AUTOMATIC,all wheel drive,4.0,"Crossover,Hatchback,Luxury",Midsize,4dr Hatchback,23,16,204,50620
11912,Acura,ZDX,2013,premium unleaded (recommended),300.0,6.0,AUTOMATIC,all wheel drive,4.0,"Crossover,Hatchback,Luxury",Midsize,4dr Hatchback,23,16,204,50920
11913,Lincoln,Zephyr,2006,regular unleaded,221.0,6.0,AUTOMATIC,front wheel drive,4.0,Luxury,Midsize,Sedan,26,17,61,28995

In [77]:
df['Make'].value_counts()

Chevrolet        1123
Ford              881
Volkswagen        809
Toyota            746
Dodge             626
Nissan            558
GMC               515
Honda             449
Mazda             423
Cadillac          397
Mercedes-Benz     353
Suzuki            351
BMW               334
Infiniti          330
Audi              328
Hyundai           303
Volvo             281
Subaru            256
Acura             252
Kia               231
Mitsubishi        213
Lexus             202
Buick             196
Chrysler          187
Pontiac           186
Lincoln           164
Oldsmobile        150
Land Rover        143
Porsche           136
Saab              111
Aston Martin       93
Plymouth           82
Bentley            74
Ferrari            69
FIAT               62
Scion              60
Maserati           58
Lamborghini        52
Rolls-Royce        31
Lotus              29
Tesla              18
HUMMER             17
Maybach            16
Alfa Romeo          5
McLaren             5
Spyker              3
Genesis             3
Bugatti             3
Name: Make, dtype: int64

In [78]:
df2 = df[df['Make'] == 'Audi']
df2['Model'].nunique()

34

In [79]:
df[df.columns[df.isna().any()]]

,Engine Fuel Type,Engine HP,Engine Cylinders,Number of Doors,Market Category
0,premium unleaded (required),335.0,6.0,2.0,"Factory Tuner,Luxury,High-Performance"
1,premium unleaded (required),300.0,6.0,2.0,"Luxury,Performance"
2,premium unleaded (required),300.0,6.0,2.0,"Luxury,High-Performance"
3,premium unleaded (required),230.0,6.0,2.0,"Luxury,Performance"
4,premium unleaded (required),230.0,6.0,2.0,Luxury
...,...,...,...,...,...
11909,premium unleaded (required),300.0,6.0,4.0,"Crossover,Hatchback,Luxury"
11910,premium unleaded (required),300.0,6.0,4.0,"Crossover,Hatchback,Luxury"
11911,premium unleaded (required),300.0,6.0,4.0,"Crossover,Hatchback,Luxury"
11912,premium unleaded (recommended),300.0,6.0,4.0,"Crossover,Hatchback,Luxury"
11913,regular unleaded,221.0,6.0,4.0,Luxury

In [80]:
df['Engine Cylinders'].median()

6.0

In [81]:
df['Engine Cylinders'].mode()

0    4.0
Name: Engine Cylinders, dtype: float64

In [82]:
df['Engine Cylinders'] = df['Engine Cylinders'].fillna(4.0)
df['Engine Cylinders'].median()

6.0

In [83]:
df1 = df[df['Make'] == 'Lotus']
df1 = df1[['Engine HP', 'Engine Cylinders']]
df1 = df1.drop_duplicates()
df1

      Engine HP  Engine Cylinders
3912      189.0               4.0
3913      218.0               4.0
3918      217.0               4.0
4216      350.0               8.0
4257      400.0               6.0
4259      276.0               6.0
4262      345.0               6.0
4292      257.0               4.0
4293      240.0               4.0

In [84]:
X = df1.to_numpy()
XTX = np.dot(X.T, X)
XTX = np.linalg.inv(XTX)
XTX

array([[ 5.53084235e-05, -2.94319825e-03],
       [-2.94319825e-03,  1.60588447e-01]])

In [85]:
y = [1100, 800, 750, 850, 1300, 1000, 1000, 1300, 800]
w = np.dot(XTX, X.T)
w = np.dot(w, y)
w[0]

4.594944810094551